### ISSUE TITLE
failed to install mongo when running mongo setup script

### ISSUE THREAD

**Issue by teamneem** [katerberg/minimal-react#17] opened 2018-09-27 23:36 UTC
Reproduction steps:
1. Ran set up script
2. Ran set up script again but using sudo
3. Got warnings about not using sudo with Homebrew, and this: "failed to install mongo"

**Comment by katerberg** [comment] 2018-10-01 17:45
This has been added to the backlog. Thanks for the feedback!

**Comment by katerberg** [comment] 2018-10-01 17:45
Closing as duplicate of https://github.com/katerberg/minimal-react/issues/15

**Closed by katerberg** 2018-10-01 17:45 UTC
